import assert from 'node:assert/strict';
import {collectPages, normalize, deduplicate, active, cpf} from '../functions/sync-quark-department/quark-core.ts';
assert.equal(cpf('529.982.247-25'),'52998224725');
assert.equal(cpf('11111111111'),'');
assert.equal(active({ativo:'false'}),false);
assert.equal(active({ativo:'true'}),true);
assert.equal(active({situacao:{denominacao:'DESLIGADO'}}),false);
assert.equal(active({}),null);
const row=normalize({id:1,pessoa:{nome:'Teste',cpfCnpj:'52998224725'},equipe:{id:7,denominacao:'DP'},ativo:true},'9417839','Natal');
assert.equal(row.quark_setor_id,'7');
assert.equal(deduplicate([row,row]).records.length,1);
assert.equal(deduplicate([row,{...row,quark_unidade_id:'OUTRA'}]).conflicts,1);
assert.equal(deduplicate([row,{...row,ativo:false,quark_unidade_id:'ANTIGA'}]).records[0].quark_unidade_id,'9417839');
const all=Array.from({length:235},(_,i)=>({id:i+1}));
assert.equal((await collectPages(async query=>{const p=Number(new URLSearchParams(query).get('page')||1);return all.slice((p-1)*100,p*100);},'fixture')).length,235);
assert.equal((await collectPages(async query=>{const p=new URLSearchParams(query);if(!p.has('offset'))return all.slice(0,100);return all.slice(Number(p.get('offset')),Number(p.get('offset'))+100);},'offset')).length,235);
await assert.rejects(()=>collectPages(async()=>all.slice(0,100),'repeated'),/paginação/);
await assert.rejects(()=>collectPages(async query=>{if(query)throw Error('API indisponível');return all.slice(0,100);},'failure'),/indisponível/);
console.log('Core: CPF, situação, conflitos, paginação e falhas passaram.');
